language: c
compiler:
    - gcc
    - clang
before_script:
    - wget https://github.com/mongodb/mongo-c-driver/releases/download/0.96.0/mongo-c-driver-0.96.0.tar.gz
    - tar -xf mongo-c-driver-0.96.0.tar.gz
    - cd mongo-c-driver-0.96.0 && ./configure && make && make install
script: ./configure && make
notifications:
    recipients:
        - lwch748@gmail.com
    email:
        on_success: change
        on_failure: always
